# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.6
      uses: actions/setup-python@v5 #You can cache and restore the dependencies using the setup-python action
      #By default, the setup-python action searches for the dependency file (requirements.txt for pip, Pipfile.lock for pipenv or poetry.lock for poetry) in the whole repository. 
      with:
        python-version: "3.12.6" #Specific Python Version
      env:
        PYTHON_VER: 3.12.6
    - name: Display Python version #Testing my matrix by printing the current Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies #You can use pip to install dependencies from the PyPI package registry before building and testing your code. 
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade ruff pytest pytest-cov tox autopep8 pyflakes pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      #After you update pip, a typical next step is to install dependencies from requirements.txt.
    - name: Lint with Ruff
      run: |
        ruff check --output-format=github .
      continue-on-error: true
    - name: Test with pytest
      run: |
        pytest --doctest-modules --junitxml=junit/test-results.xml --cov-report=xml --cov-report=html --cov=./
      continue-on-error: true
    - name: Upload results to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Run tox
      # Run tox using the version of Python in `PATH`
      run: tox -e py
    - name: Upload pytest test results
      uses: actions/upload-artifact@v4
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
      with:
        name: pytest-results-${{env.python-version }}
        path: junit/test-results-${{env.python-version }}.xml
    - name: Format python code
      run: find post_traces -name '*.py' -exec autopep8 --recursive --in-place --aggressive --aggressive {} + > autopep8_output.txt
    - name: Run Pyflakes on all Python files and save output
      run: find post_traces -name '*.py' -exec pyflakes {} + > pyflakes_output.txt
    - name: Run Pylint on all Python files and save output
      run: |
        pylint post_traces --output-format=json > pylint_output.json